// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeCommenter
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeCommenter.70e4e329-cdf4-4652-82a4-b68d4f6055d3";
        public const string Name = "Code Commenter";
        public const string Description = @"Generates summaries for functions and variables with Gemini . So you don't have to do anything.Genberate";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "CM01";
        public const string Tags = "";
    }
}
